spring:
  datasource:
    url: jdbc:sqlite:file:./db/db.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
